spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  web:
    error:
      include-stacktrace: never

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations:
      - classpath:db/migration
      - classpath:db/prod

logging:
  level:
    org.springframework.security: WARN
    org.springframework.web: WARN