
server:
  port: 8080

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/security-realm-dev}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/security-realm-dev/protocol/openid-connect/certs}
          audience: ${JWT_AUDIENCE:http://localhost:8180/realms/security-realm-dev}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # =========================
            # USUARIOS
            # =========================
            - id: usuarios
              uri: http://micro-usuarios:8081
              predicates:
                - Path=/api/*/usuarios/**
              filters:
                - StripPrefix=2

            # =========================
            # NOVEDADES
            # =========================
            - id: novedades
              uri: http://micro-novedades:5003
              predicates:
                - Path=/api/*/novedades/**
              filters:
                - StripPrefix=2

            # =========================
            # REPORTES/ESTADISTICAS
            # =========================
            - id: reportes
              uri: http://micro-reportes:5004
              predicates:
                - Path=/api/*/estadisticas/**
              filters:
                - StripPrefix=2

            # =========================
            # UBICACIONES
            # =========================
            - id: ubicaciones
              uri: http://micro-ubicaciones:8082
              predicates:
                - Path=/api/*/ubicaciones/**
              filters:
                - StripPrefix=2

# ===========================
# JWT CUSTOM CONFIG
# ===========================
jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      api-client: ${KEYCLOAK_CLIENT_ID:api-gateway}

# ===========================
# KEYCLOAK
# ===========================

keycloak:
  token-url: ${KEYCLOAK_TOKEN_URL:http://localhost:8180/realms/security-realm-dev/protocol/openid-connect/token}
  logout-url: ${KEYCLOAK_LOGOUT_URL:http://localhost:8180/realms/security-realm-dev/protocol/openid-connect/logout}
  client-id: ${KEYCLOAK_CLIENT_ID:api-gateway}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:IbFLyi0YoqRirQz1c2Bh5qB16eXh3tKg}

# ===========================
# LOGGING
# ===========================
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
    org.springframework.security: DEBUG

