package co.edu.unicauca.microreportes.capaAccesoDatos.models.enums;

public enum CategoriaEvento {
    ENFRENTAMIENTO, HOSTIGAMIENTO, ATENTADO_TERRORISTA, ATAQUE_CON_DRON,
    HOMICIDIO, SECUESTRO, RETEN_ILEGAL, BLOQUEO_DE_VIA, RECLUTAMIENTO_ILICITO,
    ACCION_DE_PROTESTA, HALLAZGO_DE_MATERIAL, OTRO
}
