INSERT INTO municipios (id_municipio, nombre) VALUES
                                                  (19001, 'POPAYÁN'),
                                                  (19022, 'ALMAGUER'),
                                                  (19050, 'ARGELIA'),
                                                  (19075, 'BALBOA'),
                                                  (19100, 'BOLÍVAR'),
                                                  (19110, 'BUENOS AIRES'),
                                                  (19130, 'CAJIBÍO'),
                                                  (19137, 'CALDONO'),
                                                  (19142, 'CALOTO'),
                                                  (19212, 'CORINTO'),
                                                  (19256, 'EL TAMBO'),
                                                  (19290, 'FLORENCIA'),
                                                  (19300, 'GUACHENÉ'),
                                                  (19318, 'GUAPI'),
                                                  (19355, 'INZÁ'),
                                                  (19364, 'JAMBALÓ'),
                                                  (19392, 'LA SIERRA'),
                                                  (19397, 'LA VEGA'),
                                                  (19418, 'LÓPEZ DE MICAY'),
                                                  (19450, 'MERCADERES'),
                                                  (19455, 'MIRANDA'),
                                                  (19473, 'MORALES'),
                                                  (19513, 'PADILLA'),
                                                  (19517, 'PÁEZ'),
                                                  (19532, 'PATÍA'),
                                                  (19533, 'PIAMONTE'),
                                                  (19548, 'PIENDAMÓ - TUNÍA'),
                                                  (19573, 'PUERTO TEJADA'),
                                                  (19585, 'PURACÉ'),
                                                  (19622, 'ROSAS'),
                                                  (19693, 'SAN SEBASTIÁN'),
                                                  (19698, 'SANTANDER DE QUILICHAO'),
                                                  (19701, 'SANTA ROSA'),
                                                  (19743, 'SILVIA'),
                                                  (19760, 'SOTARÁ PAISPAMBA'),
                                                  (19780, 'SUÁREZ'),
                                                  (19785, 'SUCRE'),
                                                  (19807, 'TIMBÍO'),
                                                  (19809, 'TIMBIQUÍ'),
                                                  (19821, 'TORIBÍO'),
                                                  (19824, 'TOTORÓ'),
                                                  (19845, 'VILLA RICA')
    ON CONFLICT (id_municipio) DO NOTHING;