spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    flyway:
        enabled: true
        baseline-on-migrate: true
        locations:
            - classpath:db/migration

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_ISSUER_URI}

jwt:
    auth:
        converter:
            api-client: ${KEYCLOAK_CLIENT_ID}
            principle-attribute: preferred_username

logging:
    level:
        org.springframework: DEBUG